-- AlterTable
ALTER TABLE "Kajasep" ALTER COLUMN "name" DROP NOT NULL;
ALTER TABLE "Kajasep" ALTER COLUMN "nickname" DROP NOT NULL;
ALTER TABLE "Kajasep" ALTER COLUMN "description" DROP NOT NULL;
ALTER TABLE "Kajasep" ALTER COLUMN "requirement" DROP NOT NULL;
ALTER TABLE "Kajasep" ALTER COLUMN "quota" DROP NOT NULL;
ALTER TABLE "Kajasep" ALTER COLUMN "totalApplicants" SET DEFAULT 0;
